export const COURSES_DATA = [
    {
      id: '1',
      title: 'HTML & CSS Fundamentals',
      description: 'Learn the building blocks of the web. Master HTML structure and CSS styling.',
      icon: '🌐',
      color: '#E44D26',
      level: 'Beginner',
      duration: '4 hours',
      lessons: [
        { id: 'l1', title: 'What is HTML?', duration: '10 min', content: 'HTML (HyperText Markup Language) is the standard language for creating web pages. It describes the structure of a web page using markup.\n\nHTML elements are the building blocks of HTML pages. They are represented by tags like <html>, <head>, <body>, <h1>, <p>, etc.\n\nExample:\n```html\n<!DOCTYPE html>\n<html>\n  <head>\n    <title>My First Page</title>\n  </head>\n  <body>\n    <h1>Hello World!</h1>\n    <p>This is my first web page.</p>\n  </body>\n</html>\n```' },
        { id: 'l2', title: 'HTML Tags & Elements', duration: '12 min', content: 'HTML tags are keywords surrounded by angle brackets. Most tags come in pairs: an opening tag and a closing tag.\n\nCommon HTML tags:\n- <h1> to <h6>: Headings\n- <p>: Paragraph\n- <a>: Anchor/Link\n- <img>: Image\n- <div>: Division\n- <span>: Inline container\n- <ul>, <ol>, <li>: Lists\n\nExample:\n```html\n<h1>Main Heading</h1>\n<p>A paragraph of text.</p>\n<a href="https://example.com">Click here</a>\n<img src="photo.jpg" alt="A photo">\n```' },
        { id: 'l3', title: 'CSS Basics', duration: '15 min', content: 'CSS (Cascading Style Sheets) controls the visual presentation of HTML elements.\n\nCSS Syntax:\n```css\nselector {\n  property: value;\n}\n```\n\nWays to add CSS:\n1. Inline: <p style="color: red;">\n2. Internal: <style> tag in <head>\n3. External: separate .css file\n\nExample:\n```css\nbody {\n  background-color: #f0f0f0;\n  font-family: Arial, sans-serif;\n}\n\nh1 {\n  color: purple;\n  font-size: 32px;\n}\n```' },
        { id: 'l4', title: 'CSS Flexbox', duration: '20 min', content: 'Flexbox is a CSS layout model that makes it easy to design flexible and responsive layouts.\n\nKey properties:\n```css\n.container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  gap: 16px;\n  flex-direction: row;\n}\n```\n\nFlex children:\n```css\n.item {\n  flex: 1;\n}\n```' },
      ],
      quiz: [
        { id: 'q1', question: 'What does HTML stand for?', options: ['HyperText Markup Language', 'High Tech Modern Language', 'HyperText Modern Links', 'Hyper Transfer Markup Language'], answer: 0 },
        { id: 'q2', question: 'Which tag is used for the largest heading?', options: ['<h6>', '<heading>', '<h1>', '<head>'], answer: 2 },
        { id: 'q3', question: 'What does CSS stand for?', options: ['Creative Style Sheets', 'Cascading Style Sheets', 'Computer Style Sheets', 'Colorful Style Sheets'], answer: 1 },
        { id: 'q4', question: 'Which CSS property controls text color?', options: ['text-color', 'font-color', 'color', 'foreground'], answer: 2 },
        { id: 'q5', question: 'What is the correct CSS display value for flexbox?', options: ['display: block', 'display: flex', 'display: grid', 'display: inline'], answer: 1 },
      ],
    },
    {
      id: '2',
      title: 'JavaScript Basics',
      description: 'Master the programming language of the web. Learn variables, functions, and more.',
      icon: '⚡',
      color: '#F7DF1E',
      level: 'Beginner',
      duration: '6 hours',
      lessons: [
        { id: 'l1', title: 'Variables & Data Types', duration: '15 min', content: 'JavaScript has three ways to declare variables:\n\n```javascript\nvar name = "John";    // old way\nlet age = 25;         // block-scoped\nconst PI = 3.14;      // constant\n```\n\nData types:\n- String: "Hello"\n- Number: 42, 3.14\n- Boolean: true, false\n- Array: [1, 2, 3]\n- Object: { key: "value" }\n- null, undefined' },
        { id: 'l2', title: 'Functions', duration: '18 min', content: 'Functions are reusable blocks of code.\n\n```javascript\n// Function declaration\nfunction greet(name) {\n  return "Hello, " + name;\n}\n\n// Arrow function\nconst greet = (name) => {\n  return `Hello, ${name}`;\n};\n\n// Short arrow function\nconst greet = name => `Hello, ${name}`;\n\n// Call the function\ngreet("Karya"); // "Hello, Karya"\n```' },
        { id: 'l3', title: 'Arrays & Objects', duration: '20 min', content: 'Arrays store ordered lists. Objects store key-value pairs.\n\n```javascript\n// Arrays\nconst fruits = ["apple", "banana", "mango"];\nfruits.push("grape");\nfruits.pop();\nfruits.length;\n\n// Array methods\nfruits.map(f => f.toUpperCase());\nfruits.filter(f => f.length > 5);\n\n// Objects\nconst user = {\n  name: "Karya",\n  age: 20,\n  greet() { return "Hi!" }\n};\nuser.name;\nuser["age"];\n```' },
        { id: 'l4', title: 'Async & Promises', duration: '25 min', content: 'JavaScript handles async operations with Promises and async/await.\n\n```javascript\n// Promise\nfetch("https://api.example.com/data")\n  .then(res => res.json())\n  .then(data => console.log(data))\n  .catch(err => console.error(err));\n\n// async/await\nasync function getData() {\n  try {\n    const res = await fetch("https://api.example.com/data");\n    const data = await res.json();\n    return data;\n  } catch (err) {\n    console.error(err);\n  }\n}\n```' },
      ],
      quiz: [
        { id: 'q1', question: 'Which keyword creates a constant variable?', options: ['var', 'let', 'const', 'static'], answer: 2 },
        { id: 'q2', question: 'What does the arrow function => do?', options: ['Creates a class', 'Defines a function', 'Imports a module', 'Creates an object'], answer: 1 },
        { id: 'q3', question: 'Which method adds an item to the END of an array?', options: ['push()', 'pop()', 'shift()', 'unshift()'], answer: 0 },
        { id: 'q4', question: 'What does async/await help with?', options: ['Styling', 'Asynchronous code', 'Database queries only', 'HTML structure'], answer: 1 },
        { id: 'q5', question: 'What is the output of: typeof "hello"?', options: ['"text"', '"word"', '"string"', '"char"'], answer: 2 },
      ],
    },
    {
      id: '3',
      title: 'React Native',
      description: 'Build cross-platform mobile apps using React Native and JavaScript.',
      icon: '⚛️',
      color: '#61DAFB',
      level: 'Intermediate',
      duration: '8 hours',
      lessons: [
        { id: 'l1', title: 'What is React Native?', duration: '10 min', content: 'React Native lets you build mobile apps using JavaScript and React. It compiles to native iOS and Android code.\n\nKey concepts:\n- Components: building blocks of UI\n- Props: data passed to components\n- State: dynamic data inside components\n\nBasic component:\n```javascript\nimport { View, Text, StyleSheet } from "react-native";\n\nexport default function App() {\n  return (\n    <View style={styles.container}>\n      <Text>Hello KaryaChat!</Text>\n    </View>\n  );\n}\n```' },
        { id: 'l2', title: 'Core Components', duration: '20 min', content: 'React Native has built-in components:\n\n```javascript\nimport {\n  View,\n  Text,\n  TextInput,\n  TouchableOpacity,\n  ScrollView,\n  FlatList,\n  Image,\n  StyleSheet,\n} from "react-native";\n```' },
        { id: 'l3', title: 'useState & useEffect', duration: '22 min', content: 'Hooks manage state and side effects.\n\n```javascript\nimport { useState, useEffect } from "react";\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  useEffect(() => {\n    console.log("Count changed:", count);\n  }, [count]);\n\n  return (\n    <TouchableOpacity onPress={() => setCount(count + 1)}>\n      <Text>Count: {count}</Text>\n    </TouchableOpacity>\n  );\n}\n```' },
      ],
      quiz: [
        { id: 'q1', question: 'React Native compiles to which platforms?', options: ['Web only', 'iOS only', 'iOS and Android', 'Windows only'], answer: 2 },
        { id: 'q2', question: 'Which component is like a <div> in React Native?', options: ['Box', 'View', 'Container', 'Frame'], answer: 1 },
        { id: 'q3', question: 'Which hook manages component state?', options: ['useEffect', 'useRef', 'useState', 'useContext'], answer: 2 },
        { id: 'q4', question: 'What is the optimized list component in React Native?', options: ['ScrollView', 'ListView', 'FlatList', 'MapView'], answer: 2 },
        { id: 'q5', question: 'What does useEffect with [] dependency run?', options: ['On every render', 'Only on mount', 'Never', 'Only on unmount'], answer: 1 },
      ],
    },
    {
      id: '4',
      title: 'Node.js & NestJS',
      description: 'Build scalable server-side applications with Node.js and the NestJS framework.',
      icon: '🟢',
      color: '#68A063',
      level: 'Intermediate',
      duration: '7 hours',
      lessons: [
        { id: 'l1', title: 'What is Node.js?', duration: '12 min', content: 'Node.js is a JavaScript runtime built on Chrome\'s V8 engine. It allows you to run JavaScript on the server.\n\nKey features:\n- Non-blocking I/O\n- Event-driven architecture\n- NPM package ecosystem\n\n```javascript\n// Simple HTTP server\nconst http = require("http");\n\nconst server = http.createServer((req, res) => {\n  res.writeHead(200, { "Content-Type": "text/plain" });\n  res.end("Hello from Node.js!");\n});\n\nserver.listen(3000);\n```' },
        { id: 'l2', title: 'NestJS Basics', duration: '20 min', content: 'NestJS is a progressive Node.js framework for building efficient server-side applications.\n\nCore concepts:\n- Modules\n- Controllers\n- Services\n- Decorators\n\n```typescript\n@Controller("users")\nexport class UsersController {\n  constructor(private usersService: UsersService) {}\n\n  @Get()\n  findAll() {\n    return this.usersService.findAll();\n  }\n\n  @Post()\n  create(@Body() dto: CreateUserDto) {\n    return this.usersService.create(dto);\n  }\n}\n```' },
      ],
      quiz: [
        { id: 'q1', question: 'What is Node.js built on?', options: ['SpiderMonkey', 'V8 Engine', 'JavaScriptCore', 'Chakra'], answer: 1 },
        { id: 'q2', question: 'Which decorator marks a NestJS controller?', options: ['@Module', '@Injectable', '@Controller', '@Service'], answer: 2 },
        { id: 'q3', question: 'What does @Injectable() do in NestJS?', options: ['Creates a route', 'Marks a provider for DI', 'Defines a module', 'Creates a guard'], answer: 1 },
        { id: 'q4', question: 'Which command creates a new NestJS project?', options: ['nest new', 'nest create', 'nest init', 'nest start'], answer: 0 },
        { id: 'q5', question: 'What is the default port for NestJS?', options: ['8080', '4000', '3000', '5000'], answer: 2 },
      ],
    },
    {
      id: '5',
      title: 'PostgreSQL & Databases',
      description: 'Learn relational databases, SQL queries, and how to design efficient schemas.',
      icon: '🗄️',
      color: '#336791',
      level: 'Intermediate',
      duration: '5 hours',
      lessons: [
        { id: 'l1', title: 'What is PostgreSQL?', duration: '10 min', content: 'PostgreSQL is a powerful open-source relational database system.\n\nKey features:\n- ACID compliant\n- Supports JSON\n- Advanced indexing\n- Full-text search\n\nBasic SQL:\n```sql\n-- Create table\nCREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  email VARCHAR(255) UNIQUE NOT NULL,\n  username VARCHAR(100) NOT NULL,\n  created_at TIMESTAMP DEFAULT NOW()\n);\n\n-- Insert\nINSERT INTO users (email, username)\nVALUES ("karya@chat.com", "karya");\n\n-- Query\nSELECT * FROM users WHERE id = 1;\n```' },
        { id: 'l2', title: 'SQL Queries', duration: '18 min', content: 'Essential SQL commands:\n\n```sql\n-- SELECT with conditions\nSELECT id, username, email\nFROM users\nWHERE created_at > NOW() - INTERVAL "7 days"\nORDER BY created_at DESC\nLIMIT 10;\n\n-- JOIN tables\nSELECT u.username, m.content\nFROM messages m\nJOIN users u ON m.sender_id = u.id\nWHERE m.room_id = "abc123";\n\n-- UPDATE\nUPDATE users\nSET username = "newname"\nWHERE id = 1;\n\n-- DELETE\nDELETE FROM users WHERE id = 1;\n```' },
      ],
      quiz: [
        { id: 'q1', question: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Language', 'Server Query Logic', 'Structured Queue List'], answer: 0 },
        { id: 'q2', question: 'Which SQL command retrieves data?', options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'], answer: 2 },
        { id: 'q3', question: 'What does PRIMARY KEY do?', options: ['Encrypts data', 'Uniquely identifies each row', 'Links two tables', 'Speeds up inserts'], answer: 1 },
        { id: 'q4', question: 'Which clause filters query results?', options: ['ORDER BY', 'GROUP BY', 'WHERE', 'HAVING'], answer: 2 },
        { id: 'q5', question: 'What does JOIN do in SQL?', options: ['Deletes records', 'Combines rows from tables', 'Creates indexes', 'Encrypts columns'], answer: 1 },
      ],
    },
  ];